package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"errors"
	"myfavouritemovies/models"
	"myfavouritemovies/repository"
	"myfavouritemovies/security"
	"myfavouritemovies/service"
	"myfavouritemovies/utils"
	"net/http"
	"time"
)

// AddUser is the resolver for the addUser field.
func (r *mutationResolver) AddUser(ctx context.Context, nickName string, userName string, password string) (*models.User, error) {
	hash, err := security.GenerateHashPassword(password)
	if err != nil {
		return nil, err
	}
	user := &models.User{
		NickName:     nickName,
		UserName:     userName,
		PasswordHash: hash,
	}
	if err := repository.AddUser(user); err != nil {
		return nil, err
	}

	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context) (bool, error) {
	userID, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return false, errUser
	}
	if err := repository.DeleteUser(userID); err != nil {
		return false, err
	}

	return true, nil
}

// UpdateNickName is the resolver for the updateNickName field.
func (r *mutationResolver) UpdateNickName(ctx context.Context, nickName string) (*models.User, error) {
	userID, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return nil, errUser
	}
  user, err := repository.GetUserByID(userID)
  if err != nil {
    return nil, err
  }
	if err := repository.UpdateNickName(user, nickName); err != nil {
		return nil, err
	}

	return user, nil
}

// UpdatePassWord is the resolver for the updatePassWord field.
func (r *mutationResolver) UpdatePassWord(ctx context.Context, password string) (*models.User, error) {
	userID, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return nil, errUser
	}
  user, err := repository.GetUserByID(userID)
  if err != nil {
    return nil, err
  }
	if err := repository.UpdatePassWord(user, password); err != nil {
		return nil, err
	}

	return user, nil
}

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, signInInput models.SignInInput) (*models.SignInRes, error) {
	if err := security.SignIn(signInInput.Username, signInInput.Password); err != nil {
		return nil, err
	}

  user, errUser := utils.GetUserByUserName(signInInput.Username)
	if errUser != nil {
		return nil, errUser
	}

	accessToken, err := security.GenerateToken(user.ID, 30*time.Second)
	if err != nil {
		return nil, err
	}

  refreshToken, err := security.GenerateToken(user.ID, time.Minute)
	if err != nil {
		return nil, err
	}

  session, errSession := repository.AddSession(&models.Session{
    ID: refreshToken.Claims.RegisteredClaims.ID,
    UserID: refreshToken.Claims.UserID,
    RefreshToken: refreshToken.Value,
    IsRevoked: false,
    ExpiresAt: refreshToken.Claims.RegisteredClaims.ExpiresAt.Time,
  })
  if errSession != nil {
    return nil, errSession
  }

  res:=&models.SignInRes{
    SessionID: session.ID,
    AccessToken: accessToken.Value,
    RefreshToken: refreshToken.Value,
    AccessTokenExpiresAt: accessToken.Claims.RegisteredClaims.ExpiresAt.Time,
    RefreshTokenExpiresAt: refreshToken.Claims.RegisteredClaims.ExpiresAt.Time,
    User: user,
  }
	writer, ok := ctx.Value("httpResponseWriter").(http.ResponseWriter)
	if !ok {
		return nil, errors.New("response writer not found")
	}
  security.SetTokensInCookie(writer, &security.Tokens{
    Access: accessToken,
    Refresh: refreshToken,
  })

	return res, nil
}

// AddFavoriteMovie is the resolver for the addFavoriteMovie field.
func (r *mutationResolver) AddFavoriteMovie(ctx context.Context, movie models.MovieInput) (*models.FavoriteMovie, error) {
	userID, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return nil, errUser
	}
	favMovie, err := repository.AddFavoriteMovie(userID, movie)
	if err != nil {
		return nil, err
	}

	return favMovie, nil
}

// DeleteFavoriteMovie is the resolver for the deleteFavoriteMovie field.
func (r *mutationResolver) DeleteFavoriteMovie(ctx context.Context, favMovieID uint) (bool, error) {
	_, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return false, errUser
	}
	if err := repository.DeleteFavoriteMovie(favMovieID); err != nil {
		return false, err
	}

	return true, nil
}

// ToggleWatchedStatus is the resolver for the toggleWatchedStatus field.
func (r *mutationResolver) ToggleWatchedStatus(ctx context.Context, favMovieID uint) (*models.FavoriteMovie, error) {
	_, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return nil, errUser
	}
	favMovie, err := repository.ToggleWatchedStatus(favMovieID)
	if err != nil {
		return nil, err
	}

	return favMovie, nil
}

// AddFavoriteGenre is the resolver for the addFavoriteGenre field.
func (r *mutationResolver) AddFavoriteGenre(ctx context.Context, genreID uint) (uint, error) {
	userID, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return 0, errUser
	}
	if err := repository.AddFavoriteGenre(userID, genreID); err != nil {
		return 0, err
	}

	return genreID, nil
}

// DeleteFavoriteGenre is the resolver for the deleteFavoriteGenre field.
func (r *mutationResolver) DeleteFavoriteGenre(ctx context.Context, genreID uint) (bool, error) {
	userID, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return false, errUser
	}
	if err := repository.DeleteFavoriteGenre(userID, genreID); err != nil {
		return false, err
	}

	return true, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context) (*models.User, error) {
	UserID, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return nil, errUser
	}
  user,err := repository.GetUserByID(UserID)
  if err != nil {
    return nil, err
  }
  
	return user, nil
}

// GetAllGenres is the resolver for the getAllGenres field.
func (r *queryResolver) GetAllGenres(ctx context.Context) ([]*models.Genre, error) {
	_, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return nil, errUser
	}
	genres, err := repository.GetAllGenres()
	if err != nil {
		return nil, err
	}

	return genres, nil
}

// GetAllFavoriteGenres is the resolver for the getAllFavoriteGenres field.
func (r *queryResolver) GetAllFavoriteGenres(ctx context.Context) ([]uint, error) {
	userID, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return []uint{}, errUser
	}
	favGenres, err := repository.GetFavoriteGenres(userID)
	if err != nil {
		return []uint{}, err
	}

	return favGenres, nil
}

// GetFavoriteMovies is the resolver for the getFavoriteMovies field.
func (r *queryResolver) GetFavoriteMovies(ctx context.Context) ([]*models.FavoriteMovie, error) {
	userID, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return nil, errUser
	}
	favMovies, err := repository.GetFavoriteMovies(userID)
	if err != nil {
		return nil, err
	}

	return favMovies, nil
}

// GetMovieDetails is the resolver for the getMovieDetails field.
func (r *queryResolver) GetMovieDetails(ctx context.Context, movieID uint) (*models.MovieDetails, error) {
	_, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return nil, errUser
	}
	movieDetails, err := service.FetchMovieDetails(movieID)
	if err != nil {
		return nil, err
	}

	return movieDetails, nil
}

// GetFilteredMovies is the resolver for the getFilteredMovies field.
func (r *queryResolver) GetFilteredMovies(ctx context.Context, filter models.MovieFilter) ([]*models.Movie, error) {
	_, errUser := utils.GetContextUserID(ctx)
	if errUser != nil {
		return nil, errUser
	}
	filteredMovies, err := service.FetchFilteredMovies(filter)
	if err != nil {
		return nil, err
	}

	return filteredMovies, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

type Resolver struct{}